### ISSUE TITLE
Booting from openstack doesn't load userdata

### ISSUE THREAD

**Issue by mudler** [rancher/os2#11]
I've tried to apply the following cloud-init in the custom user-data when creating a VM in openstack from the os2 qcow alpha12 release:

```
#cloud-config
rancherd:
  role: cluster-init
  rancherValues:
    features:
    - multi-cluster-management=true
ssh_authorized_keys:
  - github:mudler
runcmd:
  - curl -fL https://raw.githubusercontent.com/rancher/rancherd/master/install.sh | sh -
 ```

This seems to work locally, but when the machine starts from openstack I cannot login, seems ignoring my keys
